### ISSUE TITLE
C++AMP Backend for Torch

### ISSUE THREAD

**Issue by soumith** [hughperkins/clnn#1]
Hey, just so that you are aware, there's a C++AMP based torch here as well:
https://github.com/NEELMCW/MCW_CPPAMP_TORCH

thought you might be interested.

The performance is quite good of that (and they are improving it more).

**Comment by hughperkins** [comment]
Thanks.  Only just noticed this.  I turned off automatic repository watching when I joined jenkinsci two years ago, and they had like 200 repositories :-P  I've set 'watch' on this repo now though.
