### ISSUE TITLE
Error while running test-mnist2.lua 

### ISSUE THREAD

**Issue by manjunaths** [hughperkins/clnn#13]
When I try to run the mnist2 test in clnn I get this error.

```
using luaexe: luajit
model.modules[#model].padding   nil
Using Intel(R) Corporation , OpenCL platform: Intel(R) OpenCL
Using OpenCL device: Intel(R) HD Graphics
# StochasticGradient: training
luajit: ...epLearning/torch/install/share/lua/5.1/nn/Sequential.lua:44: bad argument #1 (field padW does not exist)
stack traceback:
        [C]: in function 'updateOutput'
        ...epLearning/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ...ng/torch/install/share/lua/5.1/nn/StochasticGradient.lua:35: in function 'train'
        test/test-mnist2.lua:117: in main chunk
        [C]: at 0x004058d0
```
Do you know what is happening here ?

**Comment by hughperkins** [comment]
Hmmm, seems like a discrepancy between two of your instaled libraries.  Can you `luarocks install` all the following please:
- nn
- clnn
(and I think your cltorch is already latest version)

**Comment by manjunaths** [comment]
I did a luarocks install of the above and tried the test and it failed. I git cloned the above and did a luarocks make rocks/*.spec and they still fail with the same error as above.

My cltorch is also the install of a git cloned version. So all of them are at the latest revision is what I am thinking. Anything else that I can try ?

**Comment by hughperkins** [comment]
Can you double-check the tests pass please? ie:
```
luajit -l nn -e 'nn.test()'
luajit -l clnn -e 'clnn.test()'
```

**Comment by hughperkins** [comment]
Oh... I think this is an old script, and doesnt work.  Let me see if I can fix it.  Sorry :-P

**Comment by hughperkins** [comment]
Repaired it.  Sorry about that.  If you 'luarocks install clnn', it should work now.
