### ISSUE TITLE
comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')

### ISSUE THREAD

**Issue by linkerlin** [hughperkins/clnn#14]
luajit -l clnn -e 'clnn.test()'
Running 56 tests
|_______________________________________________________  ==> Abs_backwardUsing Apple , OpenCL platform: Apple
Using OpenCL device: Iris Pro
____|___________________________________________________  ==> ClassNLLCriterionMultipleTargetTHClReduceAll.cl build log: 
<program source>:9:10: warning: unused variable 'in1'
  float *in1 = &_in1;
         ^
<program source>:10:10: warning: unused variable 'out'
  float *out = &_out;
         ^

_______________|________________________________________  ==> SoftMax_backward/tmp/luarocks_clnn-scm-1-2347/clnn/SoftMax.cpp build log: 
<program source>:38:20: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
    for (int i=0; i<get_local_size(0); i++)
                  ~^~~~~~~~~~~~~~~~~~
<program source>:63:20: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
    for (int i=0; i<get_local_size(0); i++)
                  ~^~~~~~~~~~~~~~~~~~

/tmp/luarocks_clnn-scm-1-2347/clnn/SoftMax.cpp build log: 
<program source>:38:20: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
    for (int i=0; i<get_local_size(0); i++)
                  ~^~~~~~~~~~~~~~~~~~

______________________________________________________|_  ==> mseApply_3t_0s_0pt_-2_-2_-2_*out = 0.00040675208460443 * (*in1 - *in2) build log: 
<program source>:37:12: warning: double precision constant requires cl_khr_fp64, casting to single precision
    *out = 0.00040675208460443 * (*in1 - *in2);
           ^

Apply_3t_0s_0pt_-2_-2_-2_*out = 0.00043487714720591 * (*in1 - *in2) build log: 
<program source>:37:12: warning: double precision constant requires cl_khr_fp64, casting to single precision
    *out = 0.00043487714720591 * (*in1 - *in2);
           ^

________________________________________________________  ==> Done             

Completed 88 asserts in 56 tests with 0 errors

--------------------------------------------------------------------------------

**Comment by hughperkins** [comment]
Ok. warnings about unsigned/signed comparison removed from SoftMax.cl in 27bd0df

**Comment by hughperkins** [comment]
I guess this can be closed, right?
