### ISSUE TITLE
mac build fails with "ld: library not found for -lTHC"

### ISSUE THREAD

**Issue by hughperkins** [hughperkins/clnn#22]
mac build fails with "ld: library not found for -lTHC"

https://travis-ci.org/hughperkins/clnn/builds/99839333

**Comment by hughperkins** [comment]
(Note: the pull referenced above has nothing to do with this issue)

**Comment by hughperkins** [comment]
I think this is fixed by https://github.com/hughperkins/clnn/commit/7c83307de34c291bebccb129f27aaa17e0ce406c

**Comment by salicylic** [comment]
After updating to most recent clnn version, build goes through, but now ´require 'clnn'´ fails:
´´´
th> require 'clnn'
libthclnn_searchpath	nil
...ta/Users/jan/torch/install/share/lua/5.1/clnn/THCLNN.lua:11: bad argument #1 to 'load' (string expected, got nil)
stack traceback:
	[C]: in function 'load'
	...ta/Users/jan/torch/install/share/lua/5.1/clnn/THCLNN.lua:11: in main chunk
	[C]: in function 'require'
	...Data/Users/jan/torch/install/share/lua/5.1/clnn/init.lua:5: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x010486aba0
´´´

**Comment by hughperkins** [comment]
Ah, interesting.  Getting closer :-)  Will take a look.

**Comment by hughperkins** [comment]
(created new issue for this)
