### ISSUE TITLE
CLNN master/thnn4 build error

### ISSUE THREAD

**Issue by adrienpp** [hughperkins/clnn#30]
Hi Hugh,
I believe there is a link error in the current thnn4 / master branch.
The function GET_BLOCKS is in common.h, which has been compiled correctly 

> [ 25%] Building CXX object CMakeFiles/clnn.dir/common.cpp.o
> [100%] Linking CXX shared module libTHCLNN.so
> Undefined symbols for architecture x86_64:
>   "GET_BLOCKS(THClState*, int)", referenced from:
>       _THNN_ClSpatialAveragePooling_updateOutput in SpatialAveragePooling.cpp.o

Thanks in advance for the help.

**Comment by hughperkins** [comment]
It builds ok for me.  Can you do the following and check the problem does/doesnt still occur:
```
luarocks install torch7
luarocks install nn
luarocks install cltorch
luarocks install clnn
```

**Comment by hughperkins** [comment]
Ah, seems travis has the same issue, https://travis-ci.org/hughperkins/clnn/builds/107116666  Hmmm.

**Comment by hughperkins** [comment]
Can you confirm what platform you are on please?

**Comment by adrienpp** [comment]
I am on Mac OS 10.11.3

Something I may be missing: 

> luarocks install torch7

Does not work for me (No results matching query were found.), neither with the luarocks embedded in my already installed torch, nor with the "native" luarocks from Lua 5.2.

To confirm, all the master branches are now in sync - so we can disregard the "bleeding edge" instructions?

Lastly, I ran

> luarocks install torch
> luarocks install nn
> luarocks install cltorch
> luarocks install clnn

Where clnn did not build.

**Comment by hughperkins** [comment]
sorry, I meant `luarocks install torch`, corrected this above.

**Comment by adrienpp** [comment]
Corrected as well.

**Comment by hughperkins** [comment]
> I am on Mac OS 10.11.3

yes, I think it's a problem specific to Mac OS X.  Luckily, I do have Mac OS X build on travis, so I can try .. stuff... see if I can fix it.  If you happen to have any ideas in the meantime please let me know.  It problably involves a combination of one or both of the following mac-specific things:
- symbols in one dll arent available to later dlls by default, without some work
  - and non-flat namespace doesnt help here
- undefined symbols in a dll cause an error at linktime, whereas in linux, I think they are silently ignored, unless you try calling them

**Comment by hughperkins** [comment]
Seems the symbols really are needed, so it's probably to do with the first issue.

**Comment by hughperkins** [comment]
I've moved common.cpp/.h into lib/THCLNN directory/dylib.  That hopefully eliminates the build errors with GET_BLOCKS and GET_CL_NUM_THREADS.  Then, (if those are fixed), "just" need to fix the issues with the TemplatedKernel symbols (which are in libEasylCL, I think)

**Comment by adrienpp** [comment]
Indeed, the missing symbols are now from the classes TemplatedKernel and EasyCL.

**Comment by hughperkins** [comment]
So, basically, on linux, by doing `objdump somelib.so | grep NEEDED`, starting with `build/lib/THCLNN/lib/libTHCLNN.so`, we have the following chain of dependencies:
- libTHCLNN.so => depends directly on libTHCl.so
- libTHCl.so => depends directly on libEasyCL.so

Unfortunately, libTHCLNN.so needs a couple of symbols from libEasyCL.so, and, on Mac, these are not available to libTHCLNN.so by default.  Needs some magic linking options I think.

**Comment by adrienpp** [comment]
Sorry I am not managing to understand what cmake command the rockspec file is going to trigger.
If it's C/C++ compilation only I should be able to debug.

**Comment by hughperkins** [comment]
Ah, the easiest way to try it I think is something like:
```
git clone https://github.com/hughperkins/clnn.git
cd clnn
luarocks make rocks/clnn-scm-1.rockspec
```
Once you've done this once, then you can run cmake directly:
```
cd build
make
```

**Comment by adrienpp** [comment]
Thanks, as far as I know the directory where shared libraries are looked up is different on Mac.

But it could just be that the install/lib/ torch folder does not have a libEasyCL.so, but a libEasyCL.dylib (http://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-osx)

**Comment by hughperkins** [comment]
Yeah, when I say `.so` on mac, that will sometimes be `.dylib`, sometimes `.so`, depending on the linker options supplied.

**Comment by hughperkins** [comment]
I've added EasyCL as a direct dependency of THCLNN, maybe that will help.  But I should go to bed now-ish really, so I will check in the morning.  https://github.com/hughperkins/clnn/commit/19ab3b5f8d7229cefe73e88f92782f97827ecb05

**Comment by hughperkins** [comment]
Built ok :-)  https://travis-ci.org/hughperkins/clnn/builds/107126113

**Comment by adrienpp** [comment]
Built ok too, thanks for the help.

**Comment by hughperkins** [comment]
Cool :-)
