### ISSUE TITLE
bad argument #1 to 'set' (expecting number or torch.FloatTensor or torch.FloatStorage)

### ISSUE THREAD

**Issue by maciekd** [hughperkins/clnn#35]
Hi,

Im trying to run my NN using clnn. When executing the forward pass:

            local outputs = model:forward(inputs)

I get the following error:
torch/install/share/lua/5.1/torch/Tensor.lua:458: bad argument #1 to 'set' (expecting number or torch.FloatTensor or torch.FloatStorage at /tmp/luarocks_torch-scm-1-2862/torch7/generic/Tensor.c:1125)
stack traceback:
	[C]: in function 'set'
	torch/install/share/lua/5.1/torch/Tensor.lua:458: in function 'view'
	torch/install/share/lua/5.1/nn/Reshape.lua:46: in function <torch/install/share/lua/5.1/nn/Reshape.lua:31>
	[C]: in function 'xpcall'
	torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	train.lua:272: in function 'opfunc'
	torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
	train.lua:327: in function 'train'
	train.lua:420: in main chunk
	[C]: at 0x010a141bd0

I might be missing something fundamental, not sure?

**Comment by maciekd** [comment]
called :cl() on my model, seemed to do the trick.

**Comment by hughperkins** [comment]
Cool :-)
