### ISSUE TITLE
"getting latest SpatialAveragePooling" instruction still present in README.md

### ISSUE THREAD

**Issue by sdziscool** [hughperkins/clnn#40]
clnn-avgpool has already been ported to the master and was removed from the branches, making the instructions useless while also making me confused about what i was doing wrong. The instructions should be removed.

these instructions still worked:
git clone https://github.com/hughperkins/nn.git -b avepool_plus_master nn-avepool
cd nn-avepool
luarocks make rocks/nn-scm-1.rockspec
cd ..

I used these instructions, should i reinstall torch/nn/cltorch/clnn or is adding the post master branch harmless?

**Comment by hughperkins** [comment]
Yes, sorry about that.  The good news is I've updated the instructions to remove this.  The bad news is the installation instructions have changed.  Having torch change underneath me whilst I was working and bug reports constantly flowing in for something that had changed/broken was getting old :-P  So, I've created a stable version of torch at https://github.com/hughperkins/distro/tree/distro-cl  Installation instructions are at https://github.com/hughperkins/cltorch/#installation

**Comment by sdziscool** [comment]
Wow, that's amazing.

Thanks for everything you have done so far/are doing at the moment, your work makes AMD products worth buying.

Also in your instruction at https://github.com/hughperkins/cltorch/#installation
`source ~/torch-cl/install/bin/torch-activate`
`luajit -l cltorch -e 'cltorch.test()`
an ' (apostrophe) is missing at the end.

**Comment by hughperkins** [comment]
> an ' (apostrophe) is missing at the end ;)

Thanks!  Updated.
