### ISSUE TITLE
[Feature request] SpatialMaxPooling in ceil mode

### ISSUE THREAD

**Issue by szagoruyko** [hughperkins/clnn#5]
Caffe and Torch use different max pooling, caffe does ceil when computing output size and torch does floor. We have a switch in cudnn https://github.com/soumith/cudnn.torch/blob/master/Pooling.lua#L17, floor() and ceil() functions, and ceil max-pooling is here https://github.com/szagoruyko/imagine-nn/blob/master/SpatialMaxPooling.cu, clnn needs the same switch I think

**Comment by szagoruyko** [comment]
https://github.com/torch/cunn/pull/106 has the new kernels with ceil, floor and padding support, I think kernels for clnn max pooling have to be taken from this PR.

**Comment by hughperkins** [comment]
Ok.  Not sure if I have time for this in immediate future.  Please consider submitting a PR for this.

**Comment by hughperkins** [comment]
Hi Sergey, please confirm whether you would like to implement this yourself, and use `assignee` to assign it to yourself, or whether you are hoping that I might implement it myself, and provide details on your expectations in terms of api and performance.

**Comment by szagoruyko** [comment]
Hi Hugh, this one is easy, you just copy kernels from the other PR, you can do it faster than me.

**Comment by hughperkins** [comment]
Hi Sergey, thanks.  I will take a look :-)

**Comment by hughperkins** [comment]
Hi Sergey, merged across to clnn, in `master` branch.  Please check.
